### ISSUE TITLE
Add omniauth LDAP integration / login

### ISSUE THREAD

**Issue by jrgns** [EagerELK/ditty#16]
Ditty already implements the identity login mechanism. This task is to add the [LDAP login mechanism](https://github.com/omniauth/omniauth-ldap)

* It's only available if there's a `ldap` key in the `settings` file. Use `Ditty::Services::Settings[:ldap]` to access the settings
* It populates the relevant user detail in the users table
* It captures the relevant information to tie a user to an ldap entity
* It has a checkbox or another mechanism to determine if the user is authenticating using ldap or the identity mechanism

**Comment by jrgns** [comment]
This is possible from 418a22646a2214e54e73dccd996176828a7caa72

In `config/settings.yml` add

```yaml
authentication:
  ldap:
    description: Log in with your company credentials
    icon: building
    arguments:
    - host: '1.2.3.4'
      base: 'dc=ditty, dc=io'
      port: 389
      method: plain
      title: Ditty
      bind_dn: 'user@ditty.io' # The username to log into the AD / LDAP Server
      password: 'Security!' # The password to log into the AD / LDAP Server
      uid: userprincipalname
      callback_path: '/auth/ldap/callback'
      path_prefix '/auth'
```
