### ISSUE TITLE
Add omniauth Google OAuth2 integration / login

### ISSUE THREAD

**Issue by jrgns** [EagerELK/ditty#17]
Ditty already implements the identity login mechanism. This task is to add the [Google OAuth2 login mechanism](https://github.com/zquestz/omniauth-google-oauth2)

* It's only available if there's a `google_oauth2` key in the settings file. Use `Ditty::Services::Settings[:google-oauth2]` to access the settings
* It populates the relevant user detail in the users table
* It captures the relevant information to tie a user to an ldap entity
* It show's a `login with google` icon on the login UI that starts the process

**Comment by shobhitic** [comment]
We can't have symbol with `-` character as ruby thinks you're trying to subtract it. I think the key should be either `:google_oauth2` or `"google-oauth2".

**Comment by jrgns** [comment]
@shobhitic `:google_oath2` it is, then :)

**Comment by jrgns** [comment]
This is possible from 418a22646a2214e54e73dccd996176828a7caa72

In `config/settings.yml` add

```yaml
authentication:
  google_oauth2:
    description: Log in Google
    icon: google
    arguments:
    - ENV['GOOGLE_CLIENT_ID']
    - ENV['GOOGLE_CLIENT_SECRET']
    - callback_path: '/auth/google_oauth2/callback'
      path_prefix '/auth'
```
